services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: dilithium-server
    networks:
      app-network:
        ipv4_address: 172.20.0.2
    ports:
      - "8080:8080"
    volumes:
      - ./experiments:/app/experiments

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: dilithium-client
    stdin_open: true
    tty: true
    networks:
      app-network:
        ipv4_address: 172.20.0.3
    volumes:
      - ./experiments:/app/experiments

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16